apiVersion: v1

kind: Pod

metadata:
  name: helloworld.com
  labels:
    app: helloworld

spec:
  containers:
  - name: docker-demo
    image: dreiv/docker-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
