apiVersion: v1

kind: ReplicationController

metadata:
  name: helloworld-controller

spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: docker-demo
        image: dreiv/docker-demo
        ports:
        - name: node-port
          containerPort: 3000